import type { AssessmentQuestion } from "@/features/assessment";

export const moduleSevenQuizQuestions = [
  {
    id: 1,
    kind: "single",
    points: 1,
    prompt:
      "What is the primary benefit of using a web framework like Laravel over writing raw PHP?",
    options: [
      "Lower server costs",
      "Smaller file sizes",
      "Solving common web development problems automatically",
      "Faster code execution",
      "Better database performance",
    ],
    answer: [2],
  },
  {
    id: 2,
    kind: "single",
    points: 1,
    prompt:
      "Which command installs the Laravel installer globally on your system?",
    options: [
      "artisan install laravel",
      "npm install laravel",
      "composer install laravel",
      "php install laravel",
      "composer global require laravel/installer",
    ],
    answer: [4],
  },
  {
    id: 3,
    kind: "single",
    points: 1,
    prompt: "What is the minimum PHP version required for Laravel 11?",
    options: ["PHP 7.4", "PHP 8.1", "PHP 8.3", "PHP 8.2", "PHP 8.0"],
    answer: [3],
  },
  {
    id: 4,
    kind: "single",
    points: 1,
    prompt: "Which Artisan command starts the Laravel development server?",
    options: [
      "php artisan start",
      "php artisan dev",
      "php artisan serve",
      "php artisan server",
      "php artisan run",
    ],
    answer: [2],
  },
  {
    id: 5,
    kind: "single",
    points: 1,
    prompt: "In which directory are Laravel routes for web pages defined?",
    options: ["resources", "app/routes", "routes", "app/Http", "config"],
    answer: [2],
  },
  {
    id: 6,
    kind: "single",
    points: 1,
    prompt:
      "What does this route definition do: Route::get('/posts/{id}' function($id) { return $id; })",
    options: [
      "Redirects to the posts controller",
      "Creates a dynamic route that captures the id parameter",
      "Creates a static route to the posts page",
      "Creates a POST route for form submission",
      "Defines a database query",
    ],
    answer: [1],
  },
  {
    id: 7,
    kind: "single",
    points: 1,
    prompt: "Which file contains web routes in a Laravel application?",
    options: ["web.php", "routes.web", "web.routes", "app.php", "index.php"],
    answer: [0],
  },
  {
    id: 8,
    kind: "single",
    points: 1,
    prompt: "What HTTP method does Route::post() handle?",
    options: [
      "GET requests",
      "All HTTP methods",
      "DELETE requests",
      "POST requests",
      "PUT requests",
    ],
    answer: [3],
  },
  {
    id: 9,
    kind: "single",
    points: 1,
    prompt: "Which Artisan command generates a new controller?",
    options: [
      "php artisan make:controller",
      "php artisan new:controller",
      "php artisan generate:controller",
      "php artisan create:controller",
      "php artisan build:controller",
    ],
    answer: [0],
  },
  {
    id: 10,
    kind: "single",
    points: 1,
    prompt: "What is the conventional naming pattern for Laravel controllers?",
    options: [
      "PostController",
      "postcontroller",
      "POST_CONTROLLER",
      "postController",
      "post_controller",
    ],
    answer: [0],
  },
  {
    id: 11,
    kind: "single",
    points: 1,
    prompt:
      "In Laravel's MVC pattern what is the primary responsibility of a controller?",
    options: [
      "Generate HTML output",
      "Handle CSS styling",
      "Store data in the database",
      "Validate user input",
      "Coordinate between models and views",
    ],
    answer: [4],
  },
  {
    id: 12,
    kind: "single",
    points: 1,
    prompt: "How do you pass data from a controller to a view in Laravel?",
    options: [
      "return template('name' $data)",
      "return render('name' $data)",
      "return view('name' $data)",
      "return blade('name' $data)",
      "return view('name' ['key' => $value])",
    ],
    answer: [4],
  },
  {
    id: 13,
    kind: "single",
    points: 1,
    prompt: "What does the Blade syntax {{ $variable }} automatically provide?",
    options: [
      "Error handling",
      "XSS protection through escaping",
      "Performance optimization",
      "Variable formatting",
      "Database querying",
    ],
    answer: [1],
  },
  {
    id: 14,
    kind: "single",
    points: 1,
    prompt: "Which Blade directive is used to start a conditional statement?",
    options: ["@if", "@check", "@condition", "@when", "@test"],
    answer: [0],
  },
  {
    id: 15,
    kind: "single",
    points: 1,
    prompt: "What does @extends do in a Blade template?",
    options: [
      "Loops through data",
      "Inherits from a parent layout",
      "Defines a section",
      "Includes another template",
      "Creates a component",
    ],
    answer: [1],
  },
  {
    id: 16,
    kind: "single",
    points: 1,
    prompt: "Which Blade directive creates a placeholder in a parent layout?",
    options: ["@yield", "@extends", "@include", "@section", "@placeholder"],
    answer: [0],
  },
  {
    id: 17,
    kind: "single",
    points: 1,
    prompt:
      "True or False: Laravel automatically escapes output when using {{ }} syntax in Blade templates.",
    options: ["True", "False"],
    answer: [0],
  },
  {
    id: 18,
    kind: "single",
    points: 1,
    prompt: "What is the file extension for Blade templates?",
    options: [".html", ".view", ".template", ".blade.php", ".php"],
    answer: [3],
  },
  {
    id: 19,
    kind: "single",
    points: 1,
    prompt: "Which directory contains Blade templates in a Laravel project?",
    options: [
      "storage/views",
      "resources/views",
      "public/views",
      "templates",
      "app/views",
    ],
    answer: [1],
  },
  {
    id: 20,
    kind: "single",
    points: 1,
    prompt:
      "What does the $loop variable provide inside @foreach loops in Blade?",
    options: [
      "Error messages",
      "Information about the current iteration",
      "User authentication status",
      "Performance metrics",
      "Database connection",
    ],
    answer: [1],
  },
  {
    id: 21,
    kind: "single",
    points: 1,
    prompt:
      "Which companies mentioned in the module use Laravel for their applications?",
    options: [
      "Amazon and Microsoft",
      "Google and Facebook",
      "IBM and Oracle",
      "Disney+ and Twitch",
      "Apple and Netflix",
    ],
    answer: [3],
  },
  {
    id: 22,
    kind: "single",
    points: 1,
    prompt: "Which Artisan command shows all available commands?",
    options: [
      "php artisan all",
      "php artisan show",
      "php artisan list",
      "php artisan commands",
      "php artisan help",
    ],
    answer: [2],
  },
  {
    id: 23,
    kind: "single",
    points: 1,
    prompt: "What is the purpose of route parameters in Laravel?",
    options: [
      "To improve performance",
      "To manage user sessions",
      "To connect to databases",
      "To handle form submissions",
      "To capture dynamic parts of URLs",
    ],
    answer: [4],
  },
  {
    id: 24,
    kind: "single",
    points: 1,
    prompt:
      "In professional Laravel development what is the recommended approach for organizing application logic?",
    options: [
      "Put everything in routes",
      "Mix logic with HTML",
      "Use global functions",
      "Keep controllers thin and use service classes",
      "Store logic in views",
    ],
    answer: [3],
  },
] satisfies readonly AssessmentQuestion[];

export const moduleSevenQuizTotalPoints = moduleSevenQuizQuestions.reduce(
  (total, question) => total + question.points,
  0
);
