# Use Plug'n'Play instead of node_modules
nodeLinker: pnp

pnpMode: strict

# Store the Yarn cache locally in the project (useful for Docker and CI)
enableGlobalCache: false

# Disable compression for cached packages (faster installs, especially in Docker)
compressionLevel: 0

# Use a specific version of Yarn bundled with the project
yarnPath: .yarn/releases/yarn-4.9.2.cjs
