# .github/workflows/frontend-deploy.yml
name: Frontend Production Build

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: read
    uses: ./.github/workflows/frontend-common.yml
    with:
      environment: production
      run_lint: false
      run_tests: false
      run_build: true
    secrets:
      VITE_API_URL: ${{ secrets.VITE_API_URL }}
      VITE_QUIZ_SECRET: ${{ secrets.VITE_QUIZ_SECRET }}
      VITE_SENTRY_DSN: ${{ secrets.VITE_SENTRY_DSN }}
      ACTIONS_CHECKOUT_TOKEN: ${{ secrets.ACTIONS_CHECKOUT_TOKEN }}
