# .github/workflows/frontend-tests.yml
name: Frontend Tests

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test-only:
    uses: ./.github/workflows/frontend-common.yml
    with:
      environment: production
      run_lint: false
      run_tests: true
      run_build: false
    secrets:
      VITE_ENVIRONMENT: ${{ secrets.VITE_ENVIRONMENT }}
      VITE_API_URL: ${{ secrets.VITE_API_URL }}
      VITE_QUIZ_SECRET: ${{ secrets.VITE_QUIZ_SECRET }}
      VITE_SENTRY_DSN: ${{ secrets.VITE_SENTRY_DSN }}
